### ISSUE TITLE
FrameworkProcessor branch: subclasses do not ignore `command`.

### ISSUE THREAD

**Issue by verdimrc** [verdimrc/sagemaker-python-sdk#1]
**Describe the bug**
The new `SKLearnProcessor` ignores the `command` kwarg , i.e., no-op.

**To reproduce**
Set command to anything but `python` or `python3*`, and the bootstrap script `runproc.sh` still invokes `python`.

**Expected behavior**
Bootstrap script `runproc.sh` to invoke `command`. If `command` is `None`, it'll be `python` or `python3` depending on `py_version`.

**Screenshots or logs**
N/A

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:  the framework-processor branches in this fork repo.

**Additional context**
N/A

**Comment by athewsey** [comment]
Since we already declare a `runproc_sh`, could we just parameterize the command and default it to whatever's in `runproc_sh` today?

```
python {entry_point} "$@"
```

**Comment by verdimrc** [comment]
That's a good point. Should `command` replace:

1) the `python` in `runproc.sh`, or
2) should it replace `runproc.sh` at all?

Looking at the behavior of the original `SKLearnProcessor`, where `command`=None means `["python3"]`, option (1) seems to preserve the original semantic.

**Comment by athewsey** [comment]
Yeah agree I like option 1: zipping, uploading, loading and unzipping the code bundle should be internal functionality to the 'framework processor' I think
